[package]
name = "charsetrs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "charsetrs"
path = "src/charsetrs_core/lib.rs"

[dependencies]
chardet = "0.2.4"
encoding_rs = "0.8.35"
pyo3 = { version = "0.27", features = ["extension-module"] }
